import Case from "../models/Case.js";
import Draft from "../models/Draft.js";
import { generatePdfAndSave } from "../utils/pdf.js";

export const createPdf = async (req, res) => {
  try {
    const { caseId } = req.params;

    const caseData = await Case.findById(caseId);
    if (!caseData) return res.status(404).json({ error: "Case not found" });

    const draft = await Draft.findOne({ caseId }).sort({ createdAt: -1 });
    if (!draft)
      return res.status(404).json({ error: "AI draft not found. Generate draft first." });

    // HTML TEMPLATE
   const html = `
<html>
  <head>
    <style>
      body {
        font-family: "Times New Roman", serif;
        padding: 35px;
        line-height: 1.55;
        font-size: 14px;
        background: #f7f7f7;
      }

      .page {
        background: #fff;
        padding: 35px 40px;
        border: 2px solid #000;
      }

      .title-box {
        border: 2px solid #000;
        padding: 10px;
        text-align: center;
        margin-bottom: 25px;
      }

      .title-box h1 {
        margin: 0;
        font-size: 20px;
        text-transform: uppercase;
        font-weight: bold;
      }

      .section-title {
        margin-top: 28px;
        margin-bottom: 10px;
        font-weight: bold;
        font-size: 16px;
        border-bottom: 1px solid #222;
        padding-bottom: 4px;
        text-transform: uppercase;
      }

      .field {
        margin: 3px 0;
      }

      .label {
        font-weight: bold;
      }

      .draft-box {
        border: 1px solid #999;
        padding: 15px;
        margin-top: 10px;
        white-space: pre-wrap;
      }

      .signature {
        margin-top: 50px;
        text-align: right;
        font-weight: bold;
      }

      .footer {
        margin-top: 40px;
        text-align: center;
        font-size: 12px;
        color: #777;
      }
    </style>
  </head>

  <body>
    <div class="page">

      <div class="title-box">
        <h1>Legal Draft – Jammu & Kashmir</h1>
      </div>

      <!-- CLIENT SECTION -->
      <div class="section-title">Client Information</div>
      <div class="field"><span class="label">Name:</span> ${caseData.clientName}</div>
      <div class="field"><span class="label">Phone:</span> ${caseData.phone}</div>
      <div class="field"><span class="label">Email:</span> ${caseData.email}</div>
      <div class="field"><span class="label">Address:</span> ${caseData.address}</div>

      <!-- CASE DETAILS -->
      <div class="section-title">Case Details</div>
      <div class="field"><span class="label">Case Type:</span> ${caseData.caseType}</div>
      <div class="field"><span class="label">Case Number:</span> ${caseData.caseNumber}</div>
      <div class="field"><span class="label">Court Name:</span> ${caseData.courtName}</div>
      <div class="field"><span class="label">Filing Date:</span> ${caseData.filingDate}</div>

      <!-- OPPOSING PARTY -->
      <div class="section-title">Opposing Party</div>
      <div class="field"><span class="label">Name:</span> ${caseData.opponentName}</div>
      <div class="field"><span class="label">Address:</span> ${caseData.opponentAddress}</div>

      <!-- DRAFT CONTENT -->
      <div class="section-title">Draft Content</div>
      <div class="draft-box">
        ${draft.content.replace(/\n/g, "<br/>")}
      </div>

      <div class="signature">
        Advocate’s Signature<br>
        _______________________
      </div>

      <div class="footer">
        Document auto-generated by LegalJK – ${new Date().toLocaleDateString()}
      </div>

    </div>
  </body>
</html>
`;


    const filepath = await generatePdfAndSave(caseId, html);

   return res.download(filepath, "case-draft.pdf");
  } catch (err) {
    console.error("PDF Generation Error:", err);
    return res.status(500).json({ error: "Failed to generate PDF" });
  }
};
